package capitao.techmarket.view;

import capitao.base.ClientDao;
import capitao.base.CommandeStockDao;
import capitao.techmarket.domaine.TM_Client;
import capitao.techmarket.domaine.TM_Commande;
import capitao.techmarket.domaine.TM_LigneCommande;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jonathan.capitao
 */
public class TM_ClientSelect extends javax.swing.JFrame {
    private static TM_ClientSelect MyPanWindows = null;
    public ArrayList<TM_LigneCommande> alistComp = new ArrayList<>();
    public ArrayList<TM_Client> alistClient = new ArrayList<>();
    public ArrayList<TM_Client> clientRechercher = new ArrayList<TM_Client>();
    public TM_Client cli = null;
    
            
    public static TM_ClientSelect getInstance(ArrayList<TM_LigneCommande> alistC){
        if (MyPanWindows == null){
            MyPanWindows = new TM_ClientSelect(alistC);
        }
        TM_LoginCom.getInstance(MyPanWindows.lst_Clients).setVisible(true);
        return MyPanWindows;
    }
    

    /**
     * Creates new form TM_ClientSelect
     */
    private TM_ClientSelect(ArrayList<TM_LigneCommande> alistC) {
        alistComp = alistC;
        initComponents();
        this.setLocationRelativeTo(null);
        
        alistClient = ClientDao.getListeClient();
        clientRechercher = alistClient;
        initListClient();
    }
    public void initListClient(){
        for (int i = 0; i < clientRechercher.size(); i++){
            lst_Clients.add(clientRechercher.get(i).toString());
        }
    }
    
    
    
    public void setClient(TM_Client newCli){
        this.cli = newCli;
        alistClient.add(newCli);
        clientRechercher.add(newCli);
        lst_Clients.add(newCli.toString());
        filterList(newCli);
    }
    
    public void filterList (TM_Client cliChercher){
        int id = -1;
        for (int i = 0; i < clientRechercher.size() ; i++ )  {
            if (clientRechercher.get(i).equals(cliChercher))
                id = i;
        }
        if (id > -1){
                // initialisation de la position dans l'arraylist des client ici après
            lst_Clients.select(id); // sélection du client dans la list
        }
        return ;
    }
    
    public void searchCli (){
        lst_Clients.removeAll();
        TM_Client cliSearch = new TM_Client(-1, tf_search.getText(), tf_search.getText()
                , "", "", tf_search.getText());
        clientRechercher = new ArrayList<TM_Client>();
        for (TM_Client cli : alistClient){
            if (cli.equals(cliSearch))
                clientRechercher.add(cli);
        }
        initListClient();
    }
    
    public int getLastComId(){
        return -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtValider = new javax.swing.JButton();
        tf_search = new java.awt.TextField();
        lst_Clients = new java.awt.List();
        lbFilter = new java.awt.Label();
        jbtNewCli = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMain = new javax.swing.JMenu();
        menuFermer = new javax.swing.JMenuItem();
        men_help = new javax.swing.JMenu();
        men_help_apropos1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sélection du Client à ratacher à la commande");

        jbtValider.setText("Valider");
        jbtValider.setToolTipText("Valider le choix du client concerné par la commande");
        jbtValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtValiderActionPerformed(evt);
            }
        });

        tf_search.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                tf_searchTextValueChanged(evt);
            }
        });

        lst_Clients.setEnabled(false);
        lst_Clients.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lst_ClientsItemStateChanged(evt);
            }
        });

        lbFilter.setText("Rechercher un client existant :");

        jbtNewCli.setText("Nouveau Client");
        jbtNewCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNewCliActionPerformed(evt);
            }
        });

        menuMain.setText("Fichier");

        menuFermer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        menuFermer.setText("Fermer");
        menuFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFermerActionPerformed(evt);
            }
        });
        menuMain.add(menuFermer);

        jMenuBar1.add(menuMain);

        men_help.setText("Aide");

        men_help_apropos1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        men_help_apropos1.setText("À propos");
        men_help_apropos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                men_help_apropos1ActionPerformed(evt);
            }
        });
        men_help.add(men_help_apropos1);

        jMenuBar1.add(men_help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lst_Clients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtValider, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_search, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtNewCli, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtValider)
                    .addComponent(tf_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtNewCli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lst_Clients, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtValiderActionPerformed
        if (cli != null){
            TM_Commande com = new TM_Commande(getLastComId(), cli, alistComp);
            CommandeStockDao.creeCommande(com);
            TM_FactureAutoGenerer factu = TM_FactureAutoGenerer.getInstance(com);
            factu.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un client !", "Erreur : Aucun client sélectionné", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtValiderActionPerformed

    private void jbtNewCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNewCliActionPerformed
        TM_NewClient.getInstance(this).setVisible(true);
    }//GEN-LAST:event_jbtNewCliActionPerformed

    private void lst_ClientsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lst_ClientsItemStateChanged
        cli = clientRechercher.get(lst_Clients.getSelectedIndex());
    }//GEN-LAST:event_lst_ClientsItemStateChanged

    private void men_help_apropos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_men_help_apropos1ActionPerformed
        TM_APropos.getInstance().setVisible(true);
    }//GEN-LAST:event_men_help_apropos1ActionPerformed

    private void menuFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFermerActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuFermerActionPerformed

    private void tf_searchTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_tf_searchTextValueChanged
        searchCli();
    }//GEN-LAST:event_tf_searchTextValueChanged

   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TM_FactureAutoGenerer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TM_FactureAutoGenerer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TM_FactureAutoGenerer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TM_FactureAutoGenerer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TM_ClientSelect(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbtNewCli;
    private javax.swing.JButton jbtValider;
    private java.awt.Label lbFilter;
    private java.awt.List lst_Clients;
    private javax.swing.JMenu men_help;
    private javax.swing.JMenuItem men_help_apropos1;
    private javax.swing.JMenuItem menuFermer;
    private javax.swing.JMenu menuMain;
    private java.awt.TextField tf_search;
    // End of variables declaration//GEN-END:variables
}
