/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capitao.techmarket.view;

import capitao.techmarket.domaine.TM_Composant;
import capitao.techmarket.domaine.TM_LigneCommande;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;

/**
 *
 * @author jonathan.capitao
 */
public class TM_PanierInterface extends javax.swing.JFrame {

    public static TM_PanierInterface MyPanWindows = null;
    public ArrayList<TM_LigneCommande> alistComp = new ArrayList<>();
            
    public static TM_PanierInterface getInstance(ArrayList<TM_LigneCommande> alistComp){
        if (MyPanWindows == null){
            MyPanWindows = new TM_PanierInterface();
        }
        MyPanWindows.alistComp = alistComp;
        MyPanWindows.valideur();
        MyPanWindows.initList();
        return MyPanWindows;
    }
    
    /**
     * Creates new form TM_PanierInterface
     */ 
    private TM_PanierInterface() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    private void initList(){
        double prixTot = 0.0;
        list_compoCommandes.removeAll();
        for (TM_LigneCommande lc : alistComp){
            list_compoCommandes.add(lc.toString());
            prixTot += lc.getCompo().getPrix() * lc.getQte();
        }
        Locale caLoc = new Locale("fr","CH");
        NumberFormat money = NumberFormat.getCurrencyInstance(caLoc); 
        lbTotTtc.setText("Total : "+money.format(prixTot));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list_compoCommandes = new java.awt.List();
        lb_listTitle = new javax.swing.JLabel();
        jbt_panSuppr = new javax.swing.JButton();
        jbt_panBuy = new javax.swing.JButton();
        lbTotTtc = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        men_help = new javax.swing.JMenu();
        men_help_apropos1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("État du panier");
        setLocation(new java.awt.Point(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 267));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        list_compoCommandes.setMultipleMode(true);
        list_compoCommandes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                list_compoCommandesItemStateChanged(evt);
            }
        });

        lb_listTitle.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lb_listTitle.setText("Contenu du panier");

        jbt_panSuppr.setText("Supprimer du panier");
        jbt_panSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_panSupprActionPerformed(evt);
            }
        });

        jbt_panBuy.setText("Valider le panier");
        jbt_panBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_panBuyActionPerformed(evt);
            }
        });

        lbTotTtc.setAlignment(java.awt.Label.RIGHT);
        lbTotTtc.setText("Total : ");

        men_help.setText("Aide");

        men_help_apropos1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        men_help_apropos1.setText("À propos");
        men_help_apropos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                men_help_apropos1ActionPerformed(evt);
            }
        });
        men_help.add(men_help_apropos1);

        jMenuBar1.add(men_help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lb_listTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(list_compoCommandes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 97, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbTotTtc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbt_panBuy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbt_panSuppr, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_listTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list_compoCommandes, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTotTtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_panBuy)
                    .addComponent(jbt_panSuppr))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_panBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_panBuyActionPerformed
        TM_ClientSelect cliSelect = TM_ClientSelect.getInstance(alistComp);
        cliSelect.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbt_panBuyActionPerformed

    private void men_help_apropos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_men_help_apropos1ActionPerformed
        TM_APropos.getInstance().setVisible(true);
    }//GEN-LAST:event_men_help_apropos1ActionPerformed

    private void jbt_panSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_panSupprActionPerformed
        alistComp.remove(list_compoCommandes.getSelectedIndex());
    }//GEN-LAST:event_jbt_panSupprActionPerformed

    private void list_compoCommandesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_list_compoCommandesItemStateChanged
        valideur();
    }//GEN-LAST:event_list_compoCommandesItemStateChanged

    public void valideur(){
        jbt_panSuppr.setEnabled(list_compoCommandes.getSelectedIndexes().length > 0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TM_PanierInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TM_PanierInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TM_PanierInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TM_PanierInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TM_PanierInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbt_panBuy;
    private javax.swing.JButton jbt_panSuppr;
    private java.awt.Label lbTotTtc;
    private javax.swing.JLabel lb_listTitle;
    private java.awt.List list_compoCommandes;
    private javax.swing.JMenu men_help;
    private javax.swing.JMenuItem men_help_apropos1;
    // End of variables declaration//GEN-END:variables
}
