/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capitao.techmarket.view;

import capitao.outils.filterTools;
import capitao.techmarket.domaine.TM_Composant;
import capitao.techmarket.domaine.TM_ComposantAsStock;
import capitao.techmarket.domaine.TM_ComposantType;
import capitao.techmarket.domaine.TM_Emplacement;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;

/**
 *
 * @author jonathan.capitao
 */
public class TM_Stock extends javax.swing.JFrame {

    public static TM_Stock MyWindows = null;
    public ArrayList<TM_ComposantAsStock> alistCompoToStock = new ArrayList<>();
    public ArrayList<TM_Emplacement> alistEmplacement = new ArrayList<>();
    public TM_ComposantAsStock compoActu;
    public TM_ComposantAsStock tcs_temp;
    
    public static TM_Stock getInstance(){
        if (MyWindows == null){
            MyWindows = new TM_Stock();
        }
        return MyWindows;
    }    
    
    /**
     * Creates new form TM_CRUD_Marque
     */
    private TM_Stock() {
        initComponents();
        this.setLocationRelativeTo(null);
        updateGui(false, null);
        updateData();
    }
    
    private void updateData(){
        // donnée de test
        TM_ComposantType ct = new TM_ComposantType(3, "Carte graphique");
        alistEmplacement.add(new TM_Emplacement("A1"));
        alistEmplacement.add(new TM_Emplacement("E6"));
        alistEmplacement.add(new TM_Emplacement("B1"));
        TM_Composant compTemps = new TM_Composant("NVIDIA GeForce 960",ct);
        alistCompoToStock.add(new TM_ComposantAsStock(0, 0, compTemps, alistEmplacement.get(0))); 
        compTemps = new TM_Composant("NVIDIA GeForce 980",ct);
        alistCompoToStock.add(new TM_ComposantAsStock(0, 0, compTemps, alistEmplacement.get(1))); 
        compTemps = new TM_Composant("NVIDIA GeForce 970",ct);
        alistCompoToStock.add(new TM_ComposantAsStock(0, 0, compTemps, alistEmplacement.get(2))); 
        for (int i = 0;i<alistCompoToStock.size();i++){
            listComposants.add(alistCompoToStock.get(i).getComposantConcernee().getNom());
        }
        initCombo();
    }
    
    private void updateGui(boolean stat, TM_ComposantAsStock comp){
        jbtAddStockVirtuelle.setEnabled(stat);
        jbtUpdate.setEnabled(stat);
        tfAddToVirtuelle.setEnabled(stat);
        jCbEmplacementPossible.setVisible(stat);
        tfStockPhysique.setEnabled(false);
        tfStockVirtuelle.setEnabled(false);
        if (comp!=null){
            tfStockPhysique.setText(Integer.toString(comp.getNbEnStockPhysique()));
            tfStockVirtuelle.setText(Integer.toString(comp.getNbEnStockVirtuelle()));
            jCbEmplacementPossible.setSelectedItem(comp.getEmplacement());
        } 
    }
    
    private void initCombo(){
        jCbEmplacementPossible.setModel(new DefaultComboBoxModel(alistEmplacement.toArray()));
    }
    
    private void updateComboSelect(){
        tcs_temp = alistCompoToStock.get(listComposants.getSelectedIndex());
        TM_Emplacement empl_temp = alistEmplacement.get(jCbEmplacementPossible.getSelectedIndex());
        tcs_temp.setEmplacement(empl_temp);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfStockVirtuelle = new javax.swing.JTextField();
        tfStockPhysique = new javax.swing.JTextField();
        lbStockVirtuelle = new javax.swing.JLabel();
        lbStockPhysique = new javax.swing.JLabel();
        jbtAddStockVirtuelle = new javax.swing.JButton();
        tfAddToVirtuelle = new javax.swing.JTextField();
        jbtUpdate = new javax.swing.JButton();
        listComposants = new java.awt.List();
        jCbEmplacementPossible = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMain = new javax.swing.JMenu();
        menuFermer = new javax.swing.JMenuItem();
        men_help = new javax.swing.JMenu();
        men_help_apropos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion du stock");

        lbStockVirtuelle.setText("Stock Virtuel");

        lbStockPhysique.setText("Stock Physique");

        jbtAddStockVirtuelle.setText("Commander");
        jbtAddStockVirtuelle.setToolTipText("Génere une demande d'approvisionnement correspondant à l'article concernés et met à jour le stock virtuelkle");
        jbtAddStockVirtuelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddStockVirtuelleActionPerformed(evt);
            }
        });

        tfAddToVirtuelle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfAddToVirtuelleKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfAddToVirtuelleKeyTyped(evt);
            }
        });

        jbtUpdate.setText("Approvisionnements & Livraisons");
        jbtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUpdateActionPerformed(evt);
            }
        });

        listComposants.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listComposantsItemStateChanged(evt);
            }
        });

        jCbEmplacementPossible.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCbEmplacementPossible.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbEmplacementPossibleItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Emplacement : ");

        jButton1.setText("Fermer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        menuMain.setText("Fichier");

        menuFermer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        menuFermer.setText("Fermer");
        menuFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFermerActionPerformed(evt);
            }
        });
        menuMain.add(menuFermer);

        jMenuBar1.add(menuMain);

        men_help.setText("Aide");

        men_help_apropos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        men_help_apropos.setText("À propos");
        men_help_apropos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                men_help_aproposActionPerformed(evt);
            }
        });
        men_help.add(men_help_apropos);

        jMenuBar1.add(men_help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listComposants, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbStockPhysique, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbStockVirtuelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfStockPhysique)
                                    .addComponent(tfStockVirtuelle, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtAddStockVirtuelle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAddToVirtuelle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(jCbEmplacementPossible, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfStockVirtuelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbStockVirtuelle)
                            .addComponent(jbtAddStockVirtuelle)
                            .addComponent(tfAddToVirtuelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfStockPhysique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbStockPhysique))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCbEmplacementPossible, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(listComposants, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFermerActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuFermerActionPerformed

    private void listComposantsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listComposantsItemStateChanged
        tcs_temp = alistCompoToStock.get(listComposants.getSelectedIndex());
        updateGui(true, tcs_temp ); 
        tfAddToVirtuelle.setText("1");
    }//GEN-LAST:event_listComposantsItemStateChanged

    private void jCbEmplacementPossibleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbEmplacementPossibleItemStateChanged
        updateComboSelect();
    }//GEN-LAST:event_jCbEmplacementPossibleItemStateChanged

    private void tfAddToVirtuelleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAddToVirtuelleKeyTyped
        filterTools.filterPositiveInt(evt);
    }//GEN-LAST:event_tfAddToVirtuelleKeyTyped

    private void jbtAddStockVirtuelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddStockVirtuelleActionPerformed
        tcs_temp.addStockVirtuelle(Integer.parseInt(tfAddToVirtuelle.getText()));
        updateGui(true, tcs_temp); 
    }//GEN-LAST:event_jbtAddStockVirtuelleActionPerformed

    private void tfAddToVirtuelleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAddToVirtuelleKeyReleased
        jbtAddStockVirtuelle.setEnabled((!((JTextField)evt.getSource()).getText().isEmpty()) 
                &&(Integer.parseInt(((JTextField)evt.getSource()).getText()) > 0));
    }//GEN-LAST:event_tfAddToVirtuelleKeyReleased

    private void men_help_aproposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_men_help_aproposActionPerformed
        TM_APropos.getInstance().setVisible(true);
    }//GEN-LAST:event_men_help_aproposActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdateActionPerformed
        TM_ApproLivraison appLivWindows = TM_ApproLivraison.getInstance(tcs_temp.getComposantConcernee());
        appLivWindows.setVisible(true);
    }//GEN-LAST:event_jbtUpdateActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TM_Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TM_Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TM_Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TM_Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TM_Stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCbEmplacementPossible;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbtAddStockVirtuelle;
    private javax.swing.JButton jbtUpdate;
    private javax.swing.JLabel lbStockPhysique;
    private javax.swing.JLabel lbStockVirtuelle;
    private java.awt.List listComposants;
    private javax.swing.JMenu men_help;
    private javax.swing.JMenuItem men_help_apropos;
    private javax.swing.JMenuItem menuFermer;
    private javax.swing.JMenu menuMain;
    private javax.swing.JTextField tfAddToVirtuelle;
    private javax.swing.JTextField tfStockPhysique;
    private javax.swing.JTextField tfStockVirtuelle;
    // End of variables declaration//GEN-END:variables
}
