/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capitao.techmarket.view;
import capitao.outils.importSql;
import java.io.File;
import java.sql.SQLException;
import javax.swing.*;


/**
 *
 * @author jonathan.capitao
 */
public class TM_VendeurInterface extends javax.swing.JFrame {
    
    private static TM_VendeurInterface MyWindows = null;
    
    public static TM_VendeurInterface getInstance(){
        if (MyWindows == null){
            MyWindows = new TM_VendeurInterface();
        }
        return MyWindows;
    }
    /**
     * Creates new form TM_VendeurInterface
     */
    private TM_VendeurInterface() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuBarre = new javax.swing.JMenuBar();
        menuAdmin = new javax.swing.JMenu();
        menuImport = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuQuitter = new javax.swing.JMenuItem();
        menuDonnee = new javax.swing.JMenu();
        menuComposant = new javax.swing.JMenuItem();
        menuMarque = new javax.swing.JMenuItem();
        menuSpecification = new javax.swing.JMenuItem();
        menuTypeCompo = new javax.swing.JMenuItem();
        menuStock = new javax.swing.JMenuItem();
        men_help = new javax.swing.JMenu();
        men_help_apropos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TekMarket Manager");
        setResizable(false);

        menuAdmin.setText("Administration");
        menuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminActionPerformed(evt);
            }
        });

        menuImport.setText("Import");
        menuImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuImportActionPerformed(evt);
            }
        });
        menuAdmin.add(menuImport);
        menuAdmin.add(jSeparator1);

        menuQuitter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        menuQuitter.setText("Fermer");
        menuQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuitterActionPerformed(evt);
            }
        });
        menuAdmin.add(menuQuitter);

        mainMenuBarre.add(menuAdmin);

        menuDonnee.setText("Gestion des données");
        menuDonnee.setToolTipText("Accéder aux différentes données de l'application pour les modifier");

        menuComposant.setText("Gestion des composants");
        menuComposant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuComposantActionPerformed(evt);
            }
        });
        menuDonnee.add(menuComposant);

        menuMarque.setText("Gestion des marques");
        menuMarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMarqueActionPerformed(evt);
            }
        });
        menuDonnee.add(menuMarque);

        menuSpecification.setText("Gestion des spécifications");
        menuSpecification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSpecificationActionPerformed(evt);
            }
        });
        menuDonnee.add(menuSpecification);

        menuTypeCompo.setText("Gestion des catégories de composants");
        menuTypeCompo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTypeCompoActionPerformed(evt);
            }
        });
        menuDonnee.add(menuTypeCompo);

        menuStock.setText("Gestion du stock");
        menuStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuStockActionPerformed(evt);
            }
        });
        menuDonnee.add(menuStock);

        mainMenuBarre.add(menuDonnee);

        men_help.setText("Aide");

        men_help_apropos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        men_help_apropos.setText("À propos");
        men_help_apropos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                men_help_aproposActionPerformed(evt);
            }
        });
        men_help.add(men_help_apropos);

        mainMenuBarre.add(men_help);

        setJMenuBar(mainMenuBarre);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuImportActionPerformed
        //Create a file chooser
        JFileChooser fc_import =new JFileChooser("./data");
        int result= fc_import.showOpenDialog(null);
        if(result==JFileChooser.CANCEL_OPTION)
            return;
        String BD=fc_import.getSelectedFile().getAbsolutePath();
        File fileBD = fc_import.getSelectedFile();
        try {
            importSql.resetDatabase(fileBD);
        } catch (SQLException ex) {
            System.err.println("TM_VendeurInterface.menuImportActionPerformed: " + ex.getMessage());
        } catch (Exception ex){
            System.err.println("TM_VendeurInterface.menuImportActionPerformed: " + ex.getMessage());
        }
    }//GEN-LAST:event_menuImportActionPerformed

    private void menuQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuitterActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuQuitterActionPerformed

    private void menuComposantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuComposantActionPerformed
        TM_RD_Composant compoFrame = TM_RD_Composant.getInstance();
        compoFrame.setVisible(true);
    }//GEN-LAST:event_menuComposantActionPerformed

    private void menuMarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMarqueActionPerformed
        TM_CRUD_Marque marqueFrame = TM_CRUD_Marque.getInstance();
        marqueFrame.setVisible(true);
    }//GEN-LAST:event_menuMarqueActionPerformed

    private void menuSpecificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSpecificationActionPerformed
        TM_CRUD_Specification specFrame = TM_CRUD_Specification.getInstance();
        specFrame.setVisible(true);
    }//GEN-LAST:event_menuSpecificationActionPerformed

    private void menuTypeCompoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTypeCompoActionPerformed
        TM_CRUD_CompoType cpTypeFrame = TM_CRUD_CompoType.getInstance();
        cpTypeFrame.setVisible(true);
    }//GEN-LAST:event_menuTypeCompoActionPerformed

    private void menuStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStockActionPerformed
        TM_Stock cpStock = TM_Stock.getInstance();
        cpStock.setVisible(true);
    }//GEN-LAST:event_menuStockActionPerformed

    private void men_help_aproposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_men_help_aproposActionPerformed
        TM_APropos.getInstance().setVisible(true);
    }//GEN-LAST:event_men_help_aproposActionPerformed

    private void menuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TM_VendeurInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TM_VendeurInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TM_VendeurInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TM_VendeurInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TM_VendeurInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar mainMenuBarre;
    private javax.swing.JMenu men_help;
    private javax.swing.JMenuItem men_help_apropos;
    private javax.swing.JMenu menuAdmin;
    private javax.swing.JMenuItem menuComposant;
    private javax.swing.JMenu menuDonnee;
    private javax.swing.JMenuItem menuImport;
    private javax.swing.JMenuItem menuMarque;
    private javax.swing.JMenuItem menuQuitter;
    private javax.swing.JMenuItem menuSpecification;
    private javax.swing.JMenuItem menuStock;
    private javax.swing.JMenuItem menuTypeCompo;
    // End of variables declaration//GEN-END:variables
}
